version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      DB_NAME: ${DB_NAME}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "4502:3306"
  app:
    build: ./bezkoder-app
    restart: unless-stopped
    env_file: ./.env
    environment:
      PORT: ${PORT_DB}
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      - db
    ports:
      - ${PORT}:${PORT}
    command: npm start
volumes:
  db_data:
